Do not hard-code outputprefix contents
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/txt2manwrap.sh.in b/src/prg/bash/txt2manwrap.sh.in
--- a/src/prg/bash/txt2manwrap.sh.in
+++ b/src/prg/bash/txt2manwrap.sh.in
@@ -41,6 +41,7 @@
 # 04/01/2019	MG	1.0.4	Use absolute bash path in shebang	#
 #				instead of env. Using env is OK for a 	#
 #				non-AutoTools script.			#
+# 12/01/2019	MG	1.0.5	Do not hard code outputprefix contents.	#
 #									#
 #########################################################################
 
@@ -48,21 +49,24 @@
 # Init variables #
 ##################
 script_exit_code=0
-outputprefix="txt2manwrap: "
-version="1.0.4"				# set version variable
+outputprefix="$(basename $0):"
+version="1.0.5"				# set version variable
 
 #############
 # Functions #
 #############
 
-# Output $1 to stdout or stderr depending on $2
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr == 1
+# No return value.
 output()
 {
-	if [ $2 = 0 ]
-	then
-		echo "$outputprefix$1"
+	if [ $2 = 0 ]; then
+		printf "%s %s\n" $outputprefix "$1"
 	else
-		echo "$outputprefix$1" 1>&2
+		printf "%s %s\n" $outputprefix "$1" 1>&2
 	fi
 }
 
